
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AccountManagement = lazy(() => import("./pages/AccountManagement.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Compliance = lazy(() => import("./pages/Compliance.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const RiskAssessment = lazy(() => import("./pages/RiskAssessment.tsx"));
const Signup = lazy(() => import("./pages/Signup.tsx"));
const Transactions = lazy(() => import("./pages/Transactions.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/account-management", element: <AccountManagement />},
	{ path: "/accountmanagement", element: <AccountManagement />},
	{ path: "/", element: <App />},
	{ path: "/compliance", element: <Compliance />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/login", element: <Login />},
	{ path: "/risk-assessment", element: <RiskAssessment />},
	{ path: "/riskassessment", element: <RiskAssessment />},
	{ path: "/signup", element: <Signup />},
	{ path: "/transactions", element: <Transactions />},

];
